### ISSUE TITLE
Allow additional containers in helm chart

### ISSUE THREAD

**Issue by 98jan** [btungut/azure-devops-agent-on-kubernetes#29]
Hi,

thank you very much for providing an azure-devops-agent image and helm chart, that helped me a lot to easily setup my Azure DevOps Runners.
For building docker images I needed access to the docker.sock which is with a little bit of work also doable with Kubernetes, but needs a patch with FluxCD, my manifest looks like this:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-devops-agent-docker
spec:
  chart:
    spec:
      chart: azure-devops-agent
      sourceRef:
        kind: HelmRepository
        name: btungut
        namespace: flux-system
      version: 2.1.0
  interval: 1m0s
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: azure-devops-agent-docker
              spec:
                template:
                  spec:
                    containers:
                      - name: dind
                        image: docker:27.4.1-dind
                        securityContext:
                          privileged: true
                        env:
                          - name: DOCKER_TLS_CERTDIR
                            value: /certs
                          - name: DOCKER_CERT_PATH
                            value: /certs/client
                          - name: DOCKER_TLS_VERIFY
                            value: "1"
                          - name: DOCKER_HOST
                            value: tcp://localhost:2375
                        volumeMounts:
                          - mountPath: /var/run
                            name: dind-sock
                          - mountPath: /certs/client
                            name: dind-docker-certs
                          - mountPath: /var/lib/docker
                            name: dind-storage
  values:
    agent:
      patSecret: <secret-name>
      patSecretKey: <secret-key>
      organizationUrl: <url>
      pool: <pool-name>
    # add volumes for dind
    volumes:
      - name: dind-sock
        emptyDir: {}
      - emptyDir: { }
        name: dind-docker-certs
      - emptyDir: { }
        name: dind-storage
    # mount docker.sock
    volumeMounts:
      - name: dind-sock
        mountPath: "/var/run"
    # increase resource limits to speed up build process
    resources:
      limits:
        cpu: "2"
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 2Gi
      # dind needs root permissions
      podSecurityContext:
        runAsNonRoot: false
        runAsUser: 0
```

Would it be possible to extend the helm chart to allow adding addiotional containers to the pod?

Best regards,
Jan

**Comment by btungut** [comment]
Hi @98jan ,

Are you looking for an initContainer (which runs before the main container starts) or long-lived containers that run alongside the main container with the same lifecycle?

**Comment by saisona** [comment]
@98jan You could only mount the node docker.sock as @inarix handle it this way.
```yaml
volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
volumeMounts:
  - name: dockersock
    mountPath: "/var/run/docker.sock"
```

@btungut I also created a PullRequest to fix the issue from @98jan as we also need to add this kind of feature.
