### ISSUE TITLE
Disk space Exhaustion

### ISSUE THREAD

**Issue by Kennochas** [btungut/azure-devops-agent-on-kubernetes#7]
Hello,

I am running this helm chart, and have no illusions this is an experience problem and probably missing something. This is quite literally my first K8 cluster / first Helm chart.

When my CI pipeline started, it started trying to do its thing, but very rapidly exhausted its disk space and crashed. So I am assuming I need to do something to allocate more space at it, but I am unsure of exactly what its looking for. I tried something like the following, but it errors.

Any chance you can help steer me in the right direction? If it helps any, the type of workload being shipped to this is VMware template builds with packer. It uses up a bunch of space during the build and after the artifacts are uploaded all the space is freed up.

```
volumes:
  - name: ci-data
    size: "50Gi"

volumeMounts:
  - containerpath: /azp
    volume:
      name: ci-data
      subpath: /azp
      ```
    

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): unknown field "containerpath" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): unknown field "volume" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): missing required field "name" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): missing required field "mountPath" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "size" in io.k8s.api.core.v1.Volume]

**Comment by btungut** [comment]
Hi @Kennochas,

There is an error about `containerpath` field you specified which is not documented and supported!
Could you please try the snippet below instead (with subpath and without subpath):
```
volumes:
  - name: ci-data
    size: "50Gi"

volumeMounts:
  - containerpath: /azp
    volume:
      name: ci-data
      subpath: /azp
      mountPath: /azp
```
